# Generated by Django 5.0.7 on 2024-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('RegistrationNo', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=50)),
                ('Semester', models.CharField(max_length=50)),
            ],
        ),
    ]
